### PR TITLE
Upgrade to version 3 of the Terraform AWS provider

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request upgrades the Terraform code to use to version 3 of the Terraform AWS provider.

## 💭 Motivation and Context

Version 3 of the AWS provider has been out for a while.  We don't want to get left behind.

## 🧪 Testing

All pre-commit hooks pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)
- [x] Provider upgrade

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
This PR needs some other Terraform modules to update before the tests can pass.  I will rerun the tests when it is suitable to do so.

**Comment by dav3r** [comment]
> This PR needs some other Terraform modules to update before the tests can pass. I will rerun the tests when it is suitable to do so.

See https://github.com/cisagov/molecule-iam-user-tf-module/pull/17 and https://github.com/cisagov/ci-iam-user-tf-module/pull/14.

**Comment by jsf9k** [comment]
> This PR needs some other Terraform modules to update before the tests can pass. I will rerun the tests when it is suitable to do so.

It's passing now and ready to be reviewed.

**Review by dav3r — APPROVED** [review]
Rock and roll! 
🎸  🧻

**Review by jsf9k — COMMENTED** [review]
Amazing!  Too bad my review doesn't count, though.

**Review by mcdonnnj — APPROVED** [review]
It does the things!

**Review by hillaryj — APPROVED** [review]
🎉

**Comment by dav3r** [comment]
FYI, I'm holding off on merging this PR until the latest upstream changes make it into [`skeleton-ansible-role`](https://github.com/cisagov/skeleton-ansible-role).

**Pull request merged**
