### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-ansible-role.git`](https://github.com/cisagov/skeleton-ansible-role.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by jsf9k** [comment]
Blocked until cisagov/molecule-iam-user-tf-module#25 is merged.

**Review by jsf9k — APPROVED** [review]

**Comment by jsf9k** [comment]
Actually, I realized that we don't need to merge cisagov/molecule-iam-user-tf-module#25 for everything to work as expected.  If we don't pass in a `tags` variable then that module will use the default of empty tags, which will be merged with the `default_tags` passed in via the provider.

**Review by dav3r — APPROVED** [review]
🦊

**Review by mcdonnnj — APPROVED** [review]
LGTM ✔

**Pull request merged**
